### ISSUE TITLE
Address open connections

### ISSUE THREAD

**Issue by HX-Rd** [SOLIDSoftworks/Solid.Http#19]
We have to look into how to terminate connections (set the ConnectionLeaseTimeout ) with httpclient so we don't keep the connections open forever on high traffic users of this package. We might run into problems when we have DNS changes on the services that SolidHttp is calling.

I have been looking into this a bit and I cant see any easy solutions, might have to experiment a bit to get something working. One thing that we could do ( not the nicest approach ) is to change the httpclientfactory have a expiry property and issue a new httpclient after it has expired, it will accomplish the goal but I feel there might be a better solution to this problem...

**Comment by gislikonrad** [comment]
There is a really good conversation about this here https://github.com/dotnet/corefx/issues/11224. This is only a problem when you have a hostname that changes to a different ip, but the original ip is still serving http traffic. If the original ip stops serving traffic, then the connection is closed and a dns lookup is forced. 

One comment from the thread caught my eye:

> If you connect to a machine and the TCP/HTTP connection continues to work, why should you at some point assume the server is no longer appropriate.

This rings true for me, however there might be some things we can do. I'm thinking of a couple of ways we could improve on the SolidHttpBuilder that's used and the way that the library is initialized.

**Comment by HX-Rd** [comment]
This comment 
> If you connect to a machine and the TCP/HTTP connection continues to work, why should you at some point assume the server is no longer appropriate." 
is true but does not take into consideration one very common use case. Consider the following. In case were someone is doing blue green deployment, there would be a load balancer  in front of say server A and server B. Say we start with Server A, one would take that server out of the load balancer pool. There are usually two ways of doing it. Either let Server A keep all of it's connections and don't allow new ones in, or forcing it offline, tearing down the connections that are already in place. In case of the second one, the clients that are already in transaction with Server A would get errors on there request, but the first one allows for the requests to finish and the client's calling would not notice the deployment. In case of ConnectionLeaseTimeout being -1 ( infinite ) letting the connections drain out would never work since will never release the connection.

**Comment by pshort** [comment]
I would say if you do the second type of connection bleed, you deserve to be bled.

**Comment by gislikonrad** [comment]
#25 will address this

**Comment by gislikonrad** [comment]
We're trusting the IHttpClientFactory to do this for us. 

Also, in v2.*, you can define your naming strategy for HttpClients. This name is then used to call IHttpClientFactory to get the HttpClient.
