### ISSUE TITLE
Use StringValues instead of string and overloads

### ISSUE THREAD

**Issue by HX-Rd** [SOLIDSoftworks/Solid.Http#36]
I would suggest that we would use StringValues instead of string and overloads for lists. Probably in a few places but here is an example.

public static IServiceCollection AddSolidHttpDeserializer(this IServiceCollection services, IResponseDeserializerFactory factory, string mimeType, params string[] more)

public static IServiceCollection AddSolidHttpDeserializer<TFactory>(this IServiceCollection services, string mimeType, params string[] more)

What do you think? Keep it as is or change them?

**Comment by gislikonrad** [comment]
We're using StringValues in HeaderExtensions right now.

**Comment by gislikonrad** [comment]
We also added StringValues to query parameters functionality.
