### ISSUE TITLE
Support for .Net 4.5.2

### ISSUE THREAD

**Issue by orvaratli** [SOLIDSoftworks/Solid.Http#7]
I am running .Net 4.5.2 and I am unable to install the package:
`Severity	Code	Description	Project	File	Line	Category	Suppression State
Error		Could not install package 'SolidHttp.Extensions.Json 1.0.16-RC'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by gislikonrad** [comment]
I'll have to look at whether it's possible. The reason you can't install the package is that it's targeting .Net standard 2.0. If you want to use a .Net standard 2.0 library from .Net Framework, the minimum requirement is .Net Framework 4.6.1.

**Comment by HX-Rd** [comment]
@gislikonrad Are we pursuing this? If not we should close this issue

**Comment by HX-Rd** [comment]
I'm closing this, feel free to reopen it it you see fit
